<script>
    require(["jquery", 'underscore', 'Magento_Ui/js/modal/modal'], function ($) {
        $(document).ready(function() {
            var lastHeight = 0, curHeight = 0;
            var parentBody = window.parent.document.body;
            $('.mfp-preloader', parentBody).css('display', 'none');
            $('.mfp-close', parentBody).css('display', 'block');
            $('.mfp-iframe-holder .mfp-content', parentBody).css('width', '100%');

            $('.mfp-iframe-scaler iframe', parentBody).animate({'opacity': 1}, 1000);
            $('.reviews-actions a').attr('target', '_parent');
            $('.product-social-links a').attr('target', '_parent');
            $('body').css('overflow', 'hidden');

            function recalculateHeight(animateDelay) {
                curHeight =  $('.page-wrapper').outerHeight(true);
                documentHeight =  curHeight + "px";
                if ( curHeight != lastHeight ) {
                    $('.mfp-iframe-holder .mfp-content', parentBody).animate({
                        'height': documentHeight
                    }, animateDelay);
                    lastHeight = curHeight;
                }
            }

            recalculateHeight(0);

            setInterval(function(){
                recalculateHeight(500);
            }, 1000);
        });
    });
</script>
